texto = input("Ingrese texto: ")

texto = texto.replace("a", ".- ")
texto = texto.replace("b", "-... ")
texto = texto.replace("c", "-.-. ")
texto = texto.replace("d", "-.. ")
texto = texto.replace("e", ". ")
texto = texto.replace("f", "..-. ")
texto = texto.replace("g", "--. ")
texto = texto.replace("h", ".... ")
texto = texto.replace("i", ".. ")
texto = texto.replace("j", ".--- ")
texto = texto.replace("k", "-.- ")
texto = texto.replace("l", ".-.. ")
texto = texto.replace("m", "-- ")
texto = texto.replace("n", "-. ")
texto = texto.replace("o", "--- ")
texto = texto.replace("p", ".--. ")
texto = texto.replace("q", "--.- ")
texto = texto.replace("r", ".-. ")
texto = texto.replace("s", "... ")
texto = texto.replace("t", "- ")
texto = texto.replace("u", "..- ")
texto = texto.replace("v", "...- ")
texto = texto.replace("w", ".-- ")
texto = texto.replace("x", "-..- ")
texto = texto.replace("y", "-.-- ")
texto = texto.replace("z", "--.. ")

print(f"El cifrado es: {texto}")
